In [1]:
import torch
print(torch.__version__)

2.5.1+cu124


In [2]:
if torch.cuda.is_available():
  print('GPU is availabel')
  print(f'using GPU {torch.cuda.get_device_name(0)}')
else:
  print('GPU is not availabel')

GPU is availabel
using GPU Tesla T4


## Create a Tensor

In [4]:
# using empty
x = torch.empty(2,3)
print(x)

tensor([[2.1707e-18, 7.0952e+22, 1.7748e+28],
        [1.8176e+31, 7.2708e+31, 5.0778e+31]])


In [5]:
# check type
type(x)

torch.Tensor

In [6]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand
torch.rand(2,3)

tensor([[0.5055, 0.0832, 0.6837],
        [0.8555, 0.6644, 0.6328]])

In [10]:
# manula_seed  -> in this way random value is same
torch.manual_seed(1234)
torch.rand(2,3)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])

In [13]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
# other ways
# arange
print('using range -> ',torch.arange(0,10,2))

# using linspace
print('using linespace', torch.linspace(0,10,5))

# using eyes
print('using eye-> ', torch.eye(5))

# using full
print('using full -> ', torch.full((3,3), 5))

using range ->  tensor([0, 2, 4, 6, 8])
using linespace tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
using eye->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full ->  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensors Shapes

In [16]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
x.shape

torch.Size([2, 3])

In [18]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 1, 0]])

In [19]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [20]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [22]:
torch.rand_like(x) # resion because of rand is generate float give is type integer type

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [29]:
torch.rand_like(x,dtype= torch.float32)

tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])


## Tensor Data Types

In [23]:
# find data type
x.dtype


torch.int64

In [25]:
# assign data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [27]:
torch.tensor([1.0,2.0,3.0],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [28]:
# how to change data type
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical Operations

### 1. Scaler Operations

In [31]:
x = torch.rand(2,2)
x

tensor([[0.2837, 0.6567],
        [0.2388, 0.7313]])

In [32]:
## addition
x+2

tensor([[2.2837, 2.6567],
        [2.2388, 2.7313]])

In [33]:
## substraction
x-2

tensor([[-1.7163, -1.3433],
        [-1.7612, -1.2687]])

In [34]:
## multiplactions
x*2

tensor([[0.5673, 1.3135],
        [0.4775, 1.4626]])

In [35]:
## division
x/3

tensor([[0.0946, 0.2189],
        [0.0796, 0.2438]])

In [36]:
## int division
(x+100)/3

tensor([[33.4279, 33.5522],
        [33.4129, 33.5771]])

In [37]:
## power
x**2

tensor([[0.0805, 0.4313],
        [0.0570, 0.5348]])

## 2. Element wise Operation

In [38]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.6012, 0.3043, 0.2548],
        [0.6294, 0.9665, 0.7399]])
tensor([[0.4517, 0.4757, 0.7842],
        [0.1525, 0.6662, 0.3343]])


In [39]:
## addition
a+b

tensor([[1.0529, 0.7801, 1.0389],
        [0.7819, 1.6327, 1.0743]])

In [40]:
a-b

tensor([[ 0.1495, -0.1714, -0.5294],
        [ 0.4769,  0.3003,  0.4056]])

In [41]:
a*b

tensor([[0.2716, 0.1448, 0.1998],
        [0.0960, 0.6439, 0.2474]])

In [49]:
c = torch.tensor([1,-2,-3,4])

In [50]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [51]:
# negative
torch.neg(c)

tensor([-1,  2,  3, -4])

In [52]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [53]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [54]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [55]:
# flor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [56]:
#clamp
torch.clamp(d , min = 2 , max = 2)

tensor([2., 2., 2., 2.])

## 3. Reduction Operation

In [57]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[4., 7., 2.],
        [5., 8., 6.]])

In [58]:
# sum
torch.sum(e)

tensor(32.)

In [59]:
# sum along
torch.sum(e, dim=0)

tensor([ 9., 15.,  8.])

In [60]:
torch.sum(e, dim=1)

tensor([13., 19.])

In [61]:
# mean
torch.mean(e)

tensor(5.3333)

In [62]:
torch.mean(e, dim=0)

tensor([4.5000, 7.5000, 4.0000])

In [63]:
torch.mean(e, dim=1)

tensor([4.3333, 6.3333])

In [64]:
# standard deviation
torch.std(e)

tensor(2.1602)

In [65]:
# varience
torch.var(e)

tensor(4.6667)

In [67]:
# argmax
torch.argmax(e)

tensor(4)

In [68]:
# argmin
torch.argmin(e)

tensor(2)

## Matrix Operation

In [71]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[9, 3, 3],
        [9, 0, 1]])
tensor([[2, 9],
        [7, 8],
        [6, 3]])


In [72]:
## matrix multiplaction
torch.matmul(f,g)

tensor([[ 57, 114],
        [ 24,  84]])

In [74]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])
vector1

tensor([1, 2])

In [75]:
# dot pproduct
torch.dot(vector1, vector2)

tensor(11)

In [76]:
# transpose
torch.transpose(f,0,1)

tensor([[9, 9],
        [3, 0],
        [3, 1]])

In [77]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[4., 8., 5.],
        [1., 5., 6.],
        [4., 2., 9.]])

In [78]:
# determinant
torch.det(h)

tensor(162.)

In [79]:
## inverse
torch.inverse(h)

tensor([[ 0.2037, -0.3827,  0.1420],
        [ 0.0926,  0.0988, -0.1173],
        [-0.1111,  0.1481,  0.0741]])

## 5. Comparison operations

In [80]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[3, 5, 9],
        [7, 9, 9]])
tensor([[4, 9, 8],
        [7, 4, 5]])


In [81]:
# greate then
i>j

tensor([[False, False,  True],
        [False,  True,  True]])

In [82]:
# less then
i<j

tensor([[ True,  True, False],
        [False, False, False]])

## 6.Special fuction

In [83]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[2., 8., 8.],
        [8., 8., 4.]])

In [84]:
torch.log(k)

tensor([[0.6931, 2.0794, 2.0794],
        [2.0794, 2.0794, 1.3863]])

In [85]:
torch.exp(k)

tensor([[   7.3891, 2980.9580, 2980.9580],
        [2980.9580, 2980.9580,   54.5981]])

In [86]:
torch.sqrt(k)

tensor([[1.4142, 2.8284, 2.8284],
        [2.8284, 2.8284, 2.0000]])

In [87]:
# sigmoid
torch.sigmoid(k)

tensor([[0.8808, 0.9997, 0.9997],
        [0.9997, 0.9997, 0.9820]])

In [88]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.0025, 0.5000, 0.9820],
        [0.9975, 0.5000, 0.0180]])

In [89]:
# relu
torch.relu(k)

tensor([[2., 8., 8.],
        [8., 8., 4.]])

## Inplace Operation

In [90]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6772, 0.5274, 0.6325],
        [0.0910, 0.2323, 0.7269]])
tensor([[0.1187, 0.3951, 0.7199],
        [0.7595, 0.5311, 0.6449]])


In [91]:
m+n  # it will take memory

tensor([[0.7960, 0.9225, 1.3524],
        [0.8505, 0.7634, 1.3718]])

In [92]:
# inplace change
m.add_(n)

tensor([[0.7960, 0.9225, 1.3524],
        [0.8505, 0.7634, 1.3718]])

In [93]:
torch.relu(m)

tensor([[0.7960, 0.9225, 1.3524],
        [0.8505, 0.7634, 1.3718]])

In [94]:
m.relu_()

tensor([[0.7960, 0.9225, 1.3524],
        [0.8505, 0.7634, 1.3718]])

## Copying a Tensor

In [95]:
a = torch.rand(2,3)
a

tensor([[0.7224, 0.4416, 0.3634],
        [0.8818, 0.9874, 0.7316]])

In [97]:
a = b # not this one

id(a)


140229535904400

In [98]:
id(b)

140229535904400

In [99]:
b = a.clone()

In [100]:
a

tensor([[0.4517, 0.4757, 0.7842],
        [0.1525, 0.6662, 0.3343]])

In [101]:
b

tensor([[0.4517, 0.4757, 0.7842],
        [0.1525, 0.6662, 0.3343]])

In [102]:
a[0][0] = 10

In [103]:
a

tensor([[10.0000,  0.4757,  0.7842],
        [ 0.1525,  0.6662,  0.3343]])

In [104]:
b

tensor([[0.4517, 0.4757, 0.7842],
        [0.1525, 0.6662, 0.3343]])

In [105]:
id(a)

140229535904400

In [106]:
id(b)

140229530225168

#Tensor Operation On GPU

In [107]:
torch.cuda.is_available()

True

In [108]:
device = torch.device('cuda')

In [109]:
# create a new tensor on GPU
torch.rand((2,3), device = device)

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')

In [111]:
# moving an existin tensor on GPU
a = torch.rand((2,3)) # creating tensor on cpu


In [113]:
b= a.to(device) # moving to GPU

In [114]:
b+5

tensor([[5.4297, 5.9729, 5.9739],
        [5.4533, 5.3499, 5.7428]], device='cuda:0')

## Compare cpu and GPU

In [115]:
# create random matrix on cpu
import time
size = 10000 # L
matrix_cpu1 = torch.randn(size,size)
matrix_cpu2 = torch.randn(size,size)
# measure time
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
end_time = time.time()
time_cpu = end_time - start_time
print(f"Time taken for CPU operation: {time_cpu} seconds")

# move to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
end_time = time.time()
time_gpu = end_time - start_time
print(f"Time taken for GPU operation: {time_gpu} seconds")
print(f"Speedup: {time_cpu/time_gpu}")

Time taken for CPU operation: 27.415199995040894 seconds
Time taken for GPU operation: 0.1554858684539795 seconds
Speedup: 176.31956053392216


## Reshaping Tensors

In [116]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [117]:
# reshape
a.reshape(2,2,2,2) # product of number is same as (4,4)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [118]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [119]:
b = torch.rand(2,3,4)
b

tensor([[[0.8921, 0.1603, 0.5703, 0.2473],
         [0.5904, 0.1097, 0.1681, 0.7617],
         [0.4663, 0.2257, 0.1052, 0.7080]],

        [[0.4702, 0.7677, 0.3030, 0.5617],
         [0.7393, 0.9409, 0.5381, 0.5423],
         [0.6145, 0.8964, 0.2237, 0.1800]]])

In [120]:
# permute
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [122]:
# unsqueeze
c = torch.rand(226,226,3)
c

tensor([[[0.4152, 0.2831, 0.3528],
         [0.2105, 0.1261, 0.8591],
         [0.1971, 0.1541, 0.6280],
         ...,
         [0.9639, 0.9006, 0.6611],
         [0.4733, 0.9421, 0.0871],
         [0.7610, 0.4923, 0.6347]],

        [[0.5704, 0.5080, 0.8439],
         [0.8907, 0.6957, 0.5460],
         [0.2528, 0.3535, 0.7852],
         ...,
         [0.3747, 0.4367, 0.2437],
         [0.6260, 0.7448, 0.0515],
         [0.0376, 0.7906, 0.5438]],

        [[0.3045, 0.5519, 0.0067],
         [0.1812, 0.5636, 0.6860],
         [0.1477, 0.2023, 0.8250],
         ...,
         [0.9813, 0.7766, 0.2701],
         [0.8268, 0.5321, 0.5737],
         [0.5432, 0.5624, 0.5920]],

        ...,

        [[0.1848, 0.6006, 0.0855],
         [0.5354, 0.9175, 0.4764],
         [0.4295, 0.1816, 0.7051],
         ...,
         [0.7678, 0.7787, 0.6943],
         [0.4416, 0.5214, 0.0924],
         [0.0609, 0.0807, 0.0281]],

        [[0.1366, 0.8480, 0.4278],
         [0.2423, 0.6055, 0.9160],
         [0.

In [123]:
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [125]:
# sequence
d = torch.rand(1,20)
d

tensor([[0.8176, 0.2947, 0.2423, 0.7093, 0.8961, 0.8037, 0.5925, 0.7727, 0.9969,
         0.8480, 0.1902, 0.5611, 0.4836, 0.0107, 0.9449, 0.3681, 0.0928, 0.5549,
         0.8195, 0.2847]])

In [126]:
d.squeeze(0).shape

torch.Size([20])

## Numpy and PyTorch

In [127]:
import numpy as np

In [128]:
a = torch.tensor([1,2,3,4])
a

tensor([1, 2, 3, 4])

In [130]:
b = a.numpy()
b

array([1, 2, 3, 4])

In [131]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [132]:
torch.from_numpy(c)

tensor([1, 2, 3])